### ISSUE TITLE
Website: Videos, Images, case studies

### ISSUE THREAD

**Issue by willwade** [dasher-project/dasher#131]
For the website - and ideas of for user documentation.. I'm thinking of compiling as many case studies, Videos, Images, News stories etc. Out there. 

If you have anything please let us know - dump them in this issue thread or let me know off this thread (https://github.com/willwade). 

Thanks!

**Comment by cagdasgerede** [comment]
You have already referred to this in the past, but just in case you forget:

https://www.youtube.com/channel/UC7MUABYykiQBkMnVS3NRFqw/videos

I am not sure who has the account. It would be nice if we could take that over. I sent a message to the channel but nobody replied yet.

**Comment by smoothsaling** [comment]
I am not sure how yet but I think I can help you here. I am a big fan of technology and I use Dasher for hours every day. I began preparing for life as a quadriplegic immediately after my diagnosis. I was horrified by the long term care options that were available and was fortunate to meet the CEO of a nursing home organization who wanted to create a radically new model of care. Watch this video to learn a little of my story https://youtu.be/mgYeTy8qNyY.

I have gotten a lot of media attention in the past 8 years and much of it includes at least a snippet of Dasher because the interface is so bad ass. I don't know what warrants a case study but Dasher is an integral part of my life and I will offer to help any way I can. Thank you for your work and I look forward to getting to know you.

Examples of media coverage:
https://youtu.be/fjiX8zfWO8w Featured on CNN 12/22/16
https://youtu.be/LI05dAWp9J4 Featured on Fox News (NY) 3/27/17
https://youtu.be/EXISSjo9LgE Featured on Chronicle (Boston news magazine program) 12/12/12

**Comment by cagdasgerede** [comment]
Hi Steve, @smoothsaling 

I am a software engineer and computer science researcher. I was Ada's colleague at Google. Ada also introduced me to the tool and I was intrigued. Then I read David MacKay's research articles and I got even more interested. 

I am trying to revitalize the software development efforts on the project. There are many things we need to improve technically so that we can attract new open source contributions. My goal is to improve the development environment, tools, processes etc. so that we can participate in the events such as [Google Summer of Code](https://developers.google.com/open-source/gsoc/timeline) or [hacktoberfest ](https://hacktoberfest.digitalocean.com/) where we can attract talented engineers. We can also work on improving the overall "hygiene" of the project and porting it to the new operating systems and environments.

We also need to improve the end-user experience such as the on-boarding process.

Your story is definitely very inspiring and I am really glad to hear that you can help us to improve the end-user side of things. Because this definitely needs to be end-user driven effort to prevent any type of software bloat.

Would you be ok if I share with you a Google Doc so that you can put your ideas/recommendations  in. Then, I can move them over to this GitHub repository as new issues? or If you prefer something else, please let me know.


Cagdas Gerede

**Comment by willwade** [comment]
Awesome. Thanks @smoothsaling - that's great stuff... I know of a couple of users - I'm going to try and get them on here.. Watch this space

**Comment by gavinhenderson** [comment]
Closing this issue in favour of https://github.com/dasher-project/website/issues/1

It sits better on the website
